
export const exchangeListData = [
    {
        itemId: "03f5a176-75fa-4ffa-b979-2930dadf625f",
        imageURL: "https://s3-ap-northeast-1.amazonaws.com/zerozero-storage/0b02af4b6cd55e7ebb025c1613366f7d.png",
        name: " 【迪士尼授權】紅包袋5入",
        subtitle: "內附5張精美貼紙",
        coins: 10,
        expireDateStr: "",
        expireDate: "2020/12/15",
        description: "<div class=\"text-wb\">\r\n【注意事項】\r\n兌換成功至兌換記錄<span class=\"zero-g bg-ly\">選擇商品</span>→點選【<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD84345345\" title=\"我很好\" target=\"_blank\">請點我</a>\r\n<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD8\" title=\"我很好\" target=\"_blank\">請點我</a>】\r\n填妥【商品寄送資料表單】。\r\n\r\n<ol class=\"list-group2 number-1\">\r\n<li>請填寫當初兌換之會原姓名、電話資料，以利後續審核作業。</li>\r\n<li>請於2020/1/17(五)中午12：00前提供完整個人寄送資料，逾期視同放棄，恕不退還點數。</li>\r\n<li>完成填寫後，zero zero將於3個工作天內寄出紅包袋，最晚2020/1/22前收到商品。</li>\r\n<li>若資料填寫有誤，致使無法正確寄送，均視同無條件放棄領取並自負其責。</li>\r\n<li>zero zero保有活動調整、中止之權利。</li>\r\n</ol>\r\n</div>\r\n\r\n<!--  CSS Style -->\r\n<style>\r\n/*斷行*/\r\n.text-wb{\r\n    word-break: break-all;\r\n}\r\n/*品牌色*/\r\n.zero-g{\r\n   color: #22d3c5;\r\n}\r\n.zero-r{\r\n   color: #22d3c5;\r\n}\r\n.bg-ly{\r\n   background-color: #efef78;\r\n}\r\n.bg-ly:hover{background-color: #ffff60}\r\n/*項目符號*/\r\n.number-1 {\r\n    list-style: decimal;\r\n    padding-left: 20px;\r\n}\r\n.number-2 {\r\n    list-style: decimal-leading-zero;\r\n    padding-left: 20px;\r\n}\r\n/*滑鼠移過的樣式*/\r\n.abcedefg:hover {\r\n    border: 1px gray dotted;\r\n}\r\n/*-----------------------------------------*/\r\n\r\nol.list-group,ol.list-group2 {\r\n    line-height: 25px;\r\n}\r\nol.list-group {\r\n    list-style: decimal;\r\n    padding-left: 30px;\r\n}\r\nol.list-group li {\r\n    border-bottom: 1px dotted lightgray;\r\n    padding-top: 5px;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr:nth-child(4),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(5),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(6) {\r\n    display: none;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr th {width: 35%;text-align: left !important;}\r\n.jabZET .wording {width: 100%;}\r\n.barcode {display: none;}\r\n\r\n/* Footer 調整*/\r\n@media only screen and (max-width:465px) {\r\n  div[class*=\"Footer__Container-sc\"] {display: none;}\r\n  form.Record__AppointmentForm-abqxis-2 {padding-bottom: 0px!important;}\r\n}\r\n</style>\r\n<!--  CSS Style End -->",
        eventInfo: null,
        quantity: 0,
        exchangeLimit: true,
        exchangeLimitMax: 0,
        storeUrl: null,
        itemType: null,
        itemMode: 1
    },
    {
        itemId: "03f5a176-75fa-4ffa-b979-2930dadf625f",
        imageURL: "https://s3-ap-northeast-1.amazonaws.com/zerozero-storage/0b02af4b6cd55e7ebb025c1613366f7d.png",
        name: " 【迪士尼授權】紅包袋5入",
        subtitle: "內附5張精美貼紙",
        coins: 10,
        expireDateStr: "",
        expireDate: "2020/12/15",
        description: "<div class=\"text-wb\">\r\n【注意事項】\r\n兌換成功至兌換記錄<span class=\"zero-g bg-ly\">選擇商品</span>→點選【<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD84345345\" title=\"我很好\" target=\"_blank\">請點我</a>\r\n<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD8\" title=\"我很好\" target=\"_blank\">請點我</a>】\r\n填妥【商品寄送資料表單】。\r\n\r\n<ol class=\"list-group2 number-1\">\r\n<li>請填寫當初兌換之會原姓名、電話資料，以利後續審核作業。</li>\r\n<li>請於2020/1/17(五)中午12：00前提供完整個人寄送資料，逾期視同放棄，恕不退還點數。</li>\r\n<li>完成填寫後，zero zero將於3個工作天內寄出紅包袋，最晚2020/1/22前收到商品。</li>\r\n<li>若資料填寫有誤，致使無法正確寄送，均視同無條件放棄領取並自負其責。</li>\r\n<li>zero zero保有活動調整、中止之權利。</li>\r\n</ol>\r\n</div>\r\n\r\n<!--  CSS Style -->\r\n<style>\r\n/*斷行*/\r\n.text-wb{\r\n    word-break: break-all;\r\n}\r\n/*品牌色*/\r\n.zero-g{\r\n   color: #22d3c5;\r\n}\r\n.zero-r{\r\n   color: #22d3c5;\r\n}\r\n.bg-ly{\r\n   background-color: #efef78;\r\n}\r\n.bg-ly:hover{background-color: #ffff60}\r\n/*項目符號*/\r\n.number-1 {\r\n    list-style: decimal;\r\n    padding-left: 20px;\r\n}\r\n.number-2 {\r\n    list-style: decimal-leading-zero;\r\n    padding-left: 20px;\r\n}\r\n/*滑鼠移過的樣式*/\r\n.abcedefg:hover {\r\n    border: 1px gray dotted;\r\n}\r\n/*-----------------------------------------*/\r\n\r\nol.list-group,ol.list-group2 {\r\n    line-height: 25px;\r\n}\r\nol.list-group {\r\n    list-style: decimal;\r\n    padding-left: 30px;\r\n}\r\nol.list-group li {\r\n    border-bottom: 1px dotted lightgray;\r\n    padding-top: 5px;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr:nth-child(4),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(5),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(6) {\r\n    display: none;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr th {width: 35%;text-align: left !important;}\r\n.jabZET .wording {width: 100%;}\r\n.barcode {display: none;}\r\n\r\n/* Footer 調整*/\r\n@media only screen and (max-width:465px) {\r\n  div[class*=\"Footer__Container-sc\"] {display: none;}\r\n  form.Record__AppointmentForm-abqxis-2 {padding-bottom: 0px!important;}\r\n}\r\n</style>\r\n<!--  CSS Style End -->",
        eventInfo: null,
        quantity: 0,
        exchangeLimit: true,
        exchangeLimitMax: 0,
        storeUrl: null,
        itemType: null,
        itemMode: 1
    },
    {
        itemId: "03f5a176-75fa-4ffa-b979-2930dadf625f",
        imageURL: "https://s3-ap-northeast-1.amazonaws.com/zerozero-storage/0b02af4b6cd55e7ebb025c1613366f7d.png",
        name: " 【迪士尼授權】紅包袋5入",
        subtitle: "內附5張精美貼紙",
        coins: 10,
        expireDateStr: "",
        expireDate: "2020/12/15",
        description: "<div class=\"text-wb\">\r\n【注意事項】\r\n兌換成功至兌換記錄<span class=\"zero-g bg-ly\">選擇商品</span>→點選【<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD84345345\" title=\"我很好\" target=\"_blank\">請點我</a>\r\n<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD8\" title=\"我很好\" target=\"_blank\">請點我</a>】\r\n填妥【商品寄送資料表單】。\r\n\r\n<ol class=\"list-group2 number-1\">\r\n<li>請填寫當初兌換之會原姓名、電話資料，以利後續審核作業。</li>\r\n<li>請於2020/1/17(五)中午12：00前提供完整個人寄送資料，逾期視同放棄，恕不退還點數。</li>\r\n<li>完成填寫後，zero zero將於3個工作天內寄出紅包袋，最晚2020/1/22前收到商品。</li>\r\n<li>若資料填寫有誤，致使無法正確寄送，均視同無條件放棄領取並自負其責。</li>\r\n<li>zero zero保有活動調整、中止之權利。</li>\r\n</ol>\r\n</div>\r\n\r\n<!--  CSS Style -->\r\n<style>\r\n/*斷行*/\r\n.text-wb{\r\n    word-break: break-all;\r\n}\r\n/*品牌色*/\r\n.zero-g{\r\n   color: #22d3c5;\r\n}\r\n.zero-r{\r\n   color: #22d3c5;\r\n}\r\n.bg-ly{\r\n   background-color: #efef78;\r\n}\r\n.bg-ly:hover{background-color: #ffff60}\r\n/*項目符號*/\r\n.number-1 {\r\n    list-style: decimal;\r\n    padding-left: 20px;\r\n}\r\n.number-2 {\r\n    list-style: decimal-leading-zero;\r\n    padding-left: 20px;\r\n}\r\n/*滑鼠移過的樣式*/\r\n.abcedefg:hover {\r\n    border: 1px gray dotted;\r\n}\r\n/*-----------------------------------------*/\r\n\r\nol.list-group,ol.list-group2 {\r\n    line-height: 25px;\r\n}\r\nol.list-group {\r\n    list-style: decimal;\r\n    padding-left: 30px;\r\n}\r\nol.list-group li {\r\n    border-bottom: 1px dotted lightgray;\r\n    padding-top: 5px;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr:nth-child(4),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(5),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(6) {\r\n    display: none;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr th {width: 35%;text-align: left !important;}\r\n.jabZET .wording {width: 100%;}\r\n.barcode {display: none;}\r\n\r\n/* Footer 調整*/\r\n@media only screen and (max-width:465px) {\r\n  div[class*=\"Footer__Container-sc\"] {display: none;}\r\n  form.Record__AppointmentForm-abqxis-2 {padding-bottom: 0px!important;}\r\n}\r\n</style>\r\n<!--  CSS Style End -->",
        eventInfo: null,
        quantity: 0,
        exchangeLimit: true,
        exchangeLimitMax: 0,
        storeUrl: null,
        itemType: null,
        itemMode: 1
    },
    {
        itemId: "03f5a176-75fa-4ffa-b979-2930dadf625f",
        imageURL: "https://s3-ap-northeast-1.amazonaws.com/zerozero-storage/0b02af4b6cd55e7ebb025c1613366f7d.png",
        name: " 【迪士尼授權】紅包袋5入",
        subtitle: "內附5張精美貼紙",
        coins: 10,
        expireDateStr: "",
        expireDate: "2020/12/15",
        description: "<div class=\"text-wb\">\r\n【注意事項】\r\n兌換成功至兌換記錄<span class=\"zero-g bg-ly\">選擇商品</span>→點選【<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD84345345\" title=\"我很好\" target=\"_blank\">請點我</a>\r\n<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD8\" title=\"我很好\" target=\"_blank\">請點我</a>】\r\n填妥【商品寄送資料表單】。\r\n\r\n<ol class=\"list-group2 number-1\">\r\n<li>請填寫當初兌換之會原姓名、電話資料，以利後續審核作業。</li>\r\n<li>請於2020/1/17(五)中午12：00前提供完整個人寄送資料，逾期視同放棄，恕不退還點數。</li>\r\n<li>完成填寫後，zero zero將於3個工作天內寄出紅包袋，最晚2020/1/22前收到商品。</li>\r\n<li>若資料填寫有誤，致使無法正確寄送，均視同無條件放棄領取並自負其責。</li>\r\n<li>zero zero保有活動調整、中止之權利。</li>\r\n</ol>\r\n</div>\r\n\r\n<!--  CSS Style -->\r\n<style>\r\n/*斷行*/\r\n.text-wb{\r\n    word-break: break-all;\r\n}\r\n/*品牌色*/\r\n.zero-g{\r\n   color: #22d3c5;\r\n}\r\n.zero-r{\r\n   color: #22d3c5;\r\n}\r\n.bg-ly{\r\n   background-color: #efef78;\r\n}\r\n.bg-ly:hover{background-color: #ffff60}\r\n/*項目符號*/\r\n.number-1 {\r\n    list-style: decimal;\r\n    padding-left: 20px;\r\n}\r\n.number-2 {\r\n    list-style: decimal-leading-zero;\r\n    padding-left: 20px;\r\n}\r\n/*滑鼠移過的樣式*/\r\n.abcedefg:hover {\r\n    border: 1px gray dotted;\r\n}\r\n/*-----------------------------------------*/\r\n\r\nol.list-group,ol.list-group2 {\r\n    line-height: 25px;\r\n}\r\nol.list-group {\r\n    list-style: decimal;\r\n    padding-left: 30px;\r\n}\r\nol.list-group li {\r\n    border-bottom: 1px dotted lightgray;\r\n    padding-top: 5px;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr:nth-child(4),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(5),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(6) {\r\n    display: none;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr th {width: 35%;text-align: left !important;}\r\n.jabZET .wording {width: 100%;}\r\n.barcode {display: none;}\r\n\r\n/* Footer 調整*/\r\n@media only screen and (max-width:465px) {\r\n  div[class*=\"Footer__Container-sc\"] {display: none;}\r\n  form.Record__AppointmentForm-abqxis-2 {padding-bottom: 0px!important;}\r\n}\r\n</style>\r\n<!--  CSS Style End -->",
        eventInfo: null,
        quantity: 0,
        exchangeLimit: true,
        exchangeLimitMax: 0,
        storeUrl: null,
        itemType: null,
        itemMode: 2
    },
    {
        itemId: "03f5a176-75fa-4ffa-b979-2930dadf625f",
        imageURL: "https://s3-ap-northeast-1.amazonaws.com/zerozero-storage/0b02af4b6cd55e7ebb025c1613366f7d.png",
        name: " 【迪士尼授權】紅包袋5入",
        subtitle: "內附5張精美貼紙",
        coins: 10,
        expireDateStr: "",
        expireDate: "2020/12/15",
        description: "<div class=\"text-wb\">\r\n【注意事項】\r\n兌換成功至兌換記錄<span class=\"zero-g bg-ly\">選擇商品</span>→點選【<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD84345345\" title=\"我很好\" target=\"_blank\">請點我</a>\r\n<a href=\"https://forms.gle/h1FLA1W2rX4gZsaD8\" title=\"我很好\" target=\"_blank\">請點我</a>】\r\n填妥【商品寄送資料表單】。\r\n\r\n<ol class=\"list-group2 number-1\">\r\n<li>請填寫當初兌換之會原姓名、電話資料，以利後續審核作業。</li>\r\n<li>請於2020/1/17(五)中午12：00前提供完整個人寄送資料，逾期視同放棄，恕不退還點數。</li>\r\n<li>完成填寫後，zero zero將於3個工作天內寄出紅包袋，最晚2020/1/22前收到商品。</li>\r\n<li>若資料填寫有誤，致使無法正確寄送，均視同無條件放棄領取並自負其責。</li>\r\n<li>zero zero保有活動調整、中止之權利。</li>\r\n</ol>\r\n</div>\r\n\r\n<!--  CSS Style -->\r\n<style>\r\n/*斷行*/\r\n.text-wb{\r\n    word-break: break-all;\r\n}\r\n/*品牌色*/\r\n.zero-g{\r\n   color: #22d3c5;\r\n}\r\n.zero-r{\r\n   color: #22d3c5;\r\n}\r\n.bg-ly{\r\n   background-color: #efef78;\r\n}\r\n.bg-ly:hover{background-color: #ffff60}\r\n/*項目符號*/\r\n.number-1 {\r\n    list-style: decimal;\r\n    padding-left: 20px;\r\n}\r\n.number-2 {\r\n    list-style: decimal-leading-zero;\r\n    padding-left: 20px;\r\n}\r\n/*滑鼠移過的樣式*/\r\n.abcedefg:hover {\r\n    border: 1px gray dotted;\r\n}\r\n/*-----------------------------------------*/\r\n\r\nol.list-group,ol.list-group2 {\r\n    line-height: 25px;\r\n}\r\nol.list-group {\r\n    list-style: decimal;\r\n    padding-left: 30px;\r\n}\r\nol.list-group li {\r\n    border-bottom: 1px dotted lightgray;\r\n    padding-top: 5px;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr:nth-child(4),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(5),div[class*=\"Record__ItemInfo\"] .info table tr:nth-child(6) {\r\n    display: none;\r\n}\r\n\r\ndiv[class*=\"Record__ItemInfo\"] .info table tr th {width: 35%;text-align: left !important;}\r\n.jabZET .wording {width: 100%;}\r\n.barcode {display: none;}\r\n\r\n/* Footer 調整*/\r\n@media only screen and (max-width:465px) {\r\n  div[class*=\"Footer__Container-sc\"] {display: none;}\r\n  form.Record__AppointmentForm-abqxis-2 {padding-bottom: 0px!important;}\r\n}\r\n</style>\r\n<!--  CSS Style End -->",
        eventInfo: null,
        quantity: 0,
        exchangeLimit: true,
        exchangeLimitMax: 0,
        storeUrl: null,
        itemType: null,
        itemMode: 2
    }]