import constants from 'flux-constants';

export const auth = constants([
    'LOGIN',
    "UNAUTHORIZED",
    "LOGIN_FAIL",
    "LOGOUT_SUCCESS",
    "LOGOUT_FAIL",
    "PROFILE",
    "UPDATE_PROFILE_SUCCESS",
    "UPDATE_PROFILE_FAIL",
    "UPDATE_USER_PHOTO_SUCCESS",
    "UPDATE_USER_PHOTO_FAIL",
    "UPDATE_TOKEN_SUCCESS",
    "UPDATE_TOKEN_FAIL",
    "CHECK_LOGON",
    "SEND_VERIFY_CODE",
    "SEND_VERIFY_CODE_FAILED",
    //v2.10.0
    "LOGIN_CHECK",
    "BIND_3RD_PARTY_ID",
    "BIND_3RD_PARTY_SUCCESS",
    "UNBIND_3RD_PARTY_ID",
    "SET_PHOTO_URL",
]);

export const commonType = constants([
    'GET_LOCATION_INFO_SUCCESS',
    'GET_LOCATION_INFO_FAIL',
    'GET_AREA_INFO_SUCCESS',
    'GET_AREA_INFO_FAIL',
    'MESSAGE_SUCCESS',
    'MESSAGE_FAIL',
    'UPLOAD_IMAGE_SUCCESS',
    'UPLOAD_IMAGE_FAIL',
    'DELETE_IMAGE_SUCCESS',
    'DELETE_IMAGE_FAIL',
    'UPLOAD_IMAGE_BLOCKS',
    'SUBMIT_SUBSCRIPTION',
    'UPDATE_SUBSCRIPTION',
    'SET_SWEET_ALERT',
    'ON_ALERT_CONFIRM_CLICK',
    'ON_ALERT_CANCEL_CLICK',
    'FETCH_COMPANY_PROFILE',
    'CLEAN_COMPANY_PROFILE',
    'TOGGLE_IS_LOADING'
]);

export const registerType = constants([
    'RESET_REGISTER_VALUE',
    'REGISTER_SUCCESS',
    'REGISTER_FAIL',
    'VERIFY_SUCCESS',
    'VERIFY_FAIL',
    'RESET_VERIFY_VALUE',
    'GET_VALIDATION_CODE_SUCCESS',
    'GET_VALIDATION_CODE_FAIL',
    'GET_REG_SUCCESS_DATA',
    //v2.10.0
    'MERGE_SUCCESS',
    'MERGE_FAIL',
    'VERIFY_MOBILE_SUCCESS',
    'VERIFY_MOBILE_TYPE',
    'VERIFY_MOBILE_FAIL',
]);

export const forgetPasswordType = constants([
    'FORGET_PASSWORD_SUCCESS',
    'FORGET_PASSWORD_FAIL',
    'FORGET_PASSWORD_GET_VALIDATION_CODE_SUCCESS',
    'FORGET_PASSWORD_GET_VALIDATION_CODE_FAIL',
    'FORGET_PASSWORD_RESET_SUCCESS',
    'FORGET_PASSWORD_RESET_FAIL',
    'FORGET_PASSWORD_SET_MOBILE'
]);

export const zCoinsType = constants([
    'GET_ZCOINS_SUCCESS',
    'GET_ZCOINS_FAIL',
    'SET_CRITERIA',
    //v2.10.0
    'GET_USER_TOTAL_RECORD',
]);

export const userExchangeType = constants([
    'GET_VOUCHERS_SUCCESS',
    'GET_VOUCHERS_FAIL',
    'SET_USER_EXCHANGE_CRITERIA',
    'GET_RECORD_SUCCESS',
    'GET_RECORD_FAIL',
]);

export const electronic = constants([
    'FETCH_RECYCLE_ITEMS',
    'FETCH_ELEC_COUNTY',
    'FETCH_ELEC_TOWNSHIP',
    'FETCH_BOOKING_TIME',
    'FETCH_CONTACT_TIME',
    'PERSIST_ELECTRONIC_FORM',
    'SAVE_APPOINTMENT',
    'SAVE_EVALUATION'
]);

export const carType = constants([
    'GET_RECYCLE_COUNTRIES_SUCCESS',
    'GET_RECYCLE_COUNTRIES_FAIL',
    'GET_RECYCLE_TOWNSHIPS_SUCCESS',
    'GET_RECYCLE_TOWNSHIPS_FAIL',
    'GET_REGISTER_TYPES_SUCCESS',
    'GET_REGISTER_TYPES_FAIL',
    'GET_VEHICLE_TYPES_SUCCESS',
    'GET_VEHICLE_TYPES_FAIL',
    'GET_BRANDS_SUCCESS',
    'GET_BRANDS_FAIL',
    'GET_STYLES_SUCCESS',
    'GET_STYLES_FAIL',
    'GET_DISPLACEMENTS_SUCCESS',
    'GET_DISPLACEMENTS_FAIL',
    'GET_MANUFACTURE_YEARS_SUCCESS',
    'GET_MANUFACTURE_YEARS_FAIL',
    'GET_SPECIAL_CASES_SUCCESS',
    'GET_SPECIAL_CASES_FAIL',
    'UPDATE_SPECIAL_CASES_SUCCESS',
    'UPDATE_SPECIAL_CASES_FAIL',
    'CREATE_APPOINTMENT_ORDER_SUCCESS',
    'CREATE_APPOINTMENT_ORDER_FAIL',
    'INIT_APPOINTMENT_ORDER',
    'GET_SCRAPPED_IDENTITIES_SUCCESS',
    'GET_SCRAPPED_IDENTITIES_FAIL',
    'CREATE_RESERVATION_SUCCESS',
    'CREATE_RESERVATION_FAIL',
    'UPDATE_DRAG_PAPER_SUCCESS',
    'UPDATE_DRAG_PAPER_FAIL',
    'UPDATE_SCRAP_PAPER_SUCCESS',
    'UPDATE_SCRAP_PAPER_FAIL',
    'GET_ADDITION_SUPPORTS_SUCCESS',
    'GET_ADDITION_SUPPORTS_FAIL',
    'UPDATE_SUPPORTS_SUCCESS',
    'UPDATE_SUPPORTS_FAIL',
    'GET_CAR_ORDER_DETAIL_SUCCESS',
    'GET_CAR_ORDER_DETAIL_FAIL',
    'UPDATE_CAR_ORDER_DETAIL_ORDERTYPE',
    'ACCEPT_QUOTATION_SUCCESS',
    'ACCEPT_QUOTATION_FAIL',
    'REQOUTE_QUOTATION_SUCCESS',
    'REQOUTE_QUOTATION_FAIL',
]);

export const exchangeType = constants([
    'GET_ITEM_CATEGORIES',
    'SET_SEARCH_CRITERIA',
    'SEARCH_ITEMS',
    'SEARCH_INDEX_ITEMS',
    'SET_INDEX_SEARCH_CRITERIA',
    'SEARCH_AFFORDABLE_ITEMS',
    'RESET_PAGE_TO_ONE',
    'SET_AFFORDABLE_SEARCH_CRITERIA',
    'GET_ITEM_INFO',
    'ITEM_DISCONTINUED',
    'SET_FORM_FIELD',
    'EXCHANGE_ITEM',
    'EXCHANGE_FAILED',
    'VALIDATION_FAILED',
    'LOAD_INDEX_EVENTS',
    'GET_RECORD',
    'VERIFY_CODE_3',
    'VERIFY_CODE_4',

    //v2.10.0
    'SET_TOGGLE_FEATURED_CRITERIA',
    'GET_ITEM_COLLECTIONS',
    'SET_COLLECTION_SEARCH_CRITERIA',
    'SEARCH_COLLECTION_ITEMS',
    'GET_COLLECTION',
    //兌換清單
    'GET_USER_EXCHANGE_LIST',
    'EXCHANGE_ORDER_SUCCESS',
    'EXCHANGE_LIST_STATUS',
    //ITEM INTRO
    'INCREASE_ITEM_VALUE',
    'DECREASE_ITEM_VALUE',
    'SET_ITEM_FIELD_VALUE',
]);

export const summary = constants([
    'PERSIST_SUMMARY',
    'FETCH_SUMMARY',
    'FETCH_ELECTRONIC_APPOINTMENT',
    'FETCH_ENTERPRISE_APPOINTMENT'
]);

export const enterpriseType = constants([
    'LOAD_SLIDES',
    'LOAD_SUBSCRIPTION_SOURCES',
    'SUBSCRIPTION_APPLY'
]);

export const docDestroyType = constants([
    'LOAD_COUNTIES',
    'LOAD_TOWNSHIPS',
    'SELECT_COUNTY',
    'SELECT_TOWNSHIP',
    'CHANGE_FORM_VALUE',
    'APPOINTMENT_APPLY'
]);

export const diskDestroyType = constants([
    'LOAD_COUNTIES',
    'LOAD_TOWNSHIPS',
    'SELECT_COUNTY',
    'SELECT_TOWNSHIP',
    'CHANGE_FORM_VALUE',
    'APPOINTMENT_APPLY'
]);

export const woodClearanceType = constants([
    'LOAD_COUNTIES',
    'LOAD_TOWNSHIPS',
    'LOAD_ITEMS',
    'SELECT_COUNTY',
    'SELECT_TOWNSHIP',
    'CHANGE_FORM_VALUE',
    'APPOINTMENT_APPLY'
]);

export const foodClearanceType = constants([
    'LOAD_COUNTIES',
    'LOAD_TOWNSHIPS',
    'LOAD_ITEMS',
    'LOAD_UNITS',
    'SELECT_COUNTY',
    'SELECT_TOWNSHIP',
    'CHANGE_FORM_VALUE',
    'APPOINTMENT_APPLY'
]);

export const sludgeTreatmentType = constants([
    'LOAD_COUNTIES',
    'LOAD_TOWNSHIPS',
    'LOAD_ITEMS',
    'LOAD_PACK_TYPES',
    'SELECT_COUNTY',
    'SELECT_TOWNSHIP',
    'CHANGE_FORM_VALUE',
    'APPOINTMENT_APPLY'
]);

export const dashBoardType = constants([
    'GET_YOUTUBE_SUCCESS',
    'GET_YOUTUBE_FAIL',
    'GET_ACTIVITY_INFOS_SUCCESS',
    'GET_ACTIVITY_INFOS_FAIL',
    'GET_BANNERS_SUCCESS',
    'GET_BANNERS_FAIL',
    'GET_USER_ZCOINS',
]);

export const recycleMap = constants([
    'GET_CATEGORIES',
    'GET_RECYCLE_ITEMS',
    'GET_RECYCLE_UNITS',
    'GET_RECYCLE_UNIT_DETAIL',
    'GET_RECYCLE_UNIT_COMMENT',
    'GET_CHECK_IN_RECORDS',
    'FILTER_RECYCLE_ITEMS',
    'GET_RECYCLE_CAR',
    'GET_RECYCLE_SENSOR',
]);

export const dynamicEvent = constants([
   'GET_EVENT_CONTENT',
   'INVALID_EVENT'
]);
